SQS Receiver - Update Disposal
RockLib/RockLib.Messaging pull request #158
Opened 2022-11-16 16:03 UTC by pjwilliams2

## Description
1. Updates receiver disposal to incorporate a cancellation token for propagation to the underlying SQS client
2. Updates receiver to terminate processing when cancellation has been requested by disposal
3. Prevent multiple disposals

## Type of change: 2. Bug fix (non-breaking change that fixes an issue)

2022-11-16 16:04 UTC, pjwilliams2 commented on RockLib.Messaging.SQS/SQSReceiver.cs
> +                _consumerToken.Token);
Real change here - passing of token. All others formatting.

2022-11-16 16:23 UTC, kristycurrier approved these changes

2022-11-16 16:26 UTC, kristycurrier requested changes
Step for unit tests is failing. Looks like:
`warning : The .NET SDK has newer analyzers with version '7.0.0' than what version '6.0.0' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference. `

2022-11-16 16:49 UTC, NeilSchiefer commented
> Should there be tests around this change?

If we can.  I've found it really difficult to mock things and test the way I want to because of the way these Messaging libraries were designed.

2022-11-16 19:17 UTC, pjwilliams2 commented
> Should there be tests around this change?

Yes, updated to have some.

2022-11-16 19:36 UTC, NeilSchiefer approved these changes

2022-11-28 20:25 UTC, kristycurrier approved these changes

2022-11-28 20:29 UTC, eslutz approved these changes

2022-11-28 20:37 UTC, merged